name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{ secrets.CDN_LIBS_AWS_BUCKET_NAME }}
      CLOUDFRONT: ${{ secrets.CDN_AWS_DISTRIBUTION_ID }}
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          scope: '@libercapital'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.CDN_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CDN_AWS_SECRET_ACCESS_KEY }}
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: aws s3 sync ./lib s3://$BUCKET/libs/acquirers/$VERSION --delete
